In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('drive/MyDrive/balance-scale.data', names=['balance', 'v1', 'v2', 'v3', 'v4'])
df.head(5)

balance  v1  v2  v3  v4
0       B   1   1   1   1
1       R   1   1   1   2
2       R   1   1   1   3
3       R   1   1   1   4
4       R   1   1   1   5

In [3]:
df['balance']=df['balance']=='B'

In [5]:
df['balance'] = df['balance'].astype(int)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [8]:
y=df.balance
X = df.drop('balance', axis=1)

In [9]:
lr = LogisticRegression().fit(X, y)

In [10]:
pred_y = lr.predict(X)

In [11]:
print(accuracy_score(pred_y, y))

0.9216


In [12]:
pred_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [13]:
from sklearn.utils import resample

In [14]:
df_maj = df[df.balance==0]
df_min = df[df.balance==1]

In [17]:
df_min_upsample = resample(df_min, replace=True, n_samples=576, random_state=42)

In [24]:
df_upsample = pd.concat([df_maj, df_min_upsample])

In [25]:
X_upsample = df_upsample.drop('balance', axis=1)
y_upsample = df_upsample['balance']

In [26]:
lr_upsample = LogisticRegression().fit(X_upsample, y_upsample)

In [27]:
y_upsample_pred = lr_upsample.predict(X_upsample)

In [28]:
accuracy_score(y_upsample_pred, y_upsample)

0.5269097222222222

In [29]:
y_upsample_pred

array([1, 1, 0, ..., 0, 0, 0])

In [33]:
df_maj_downsample = resample(df_maj, replace=False, n_samples=49, random_state=42)

In [34]:
df_downsample = pd.concat([df_maj_downsample, df_min])
X_downsample = df_downsample.drop('balance', axis=1)
y_downsample = df_downsample['balance']


In [35]:
lr_downsample = LogisticRegression().fit(X_downsample, y_downsample)

In [36]:
y_downsample_pred = lr_downsample.predict(X_downsample)

In [37]:
accuracy_score(y_downsample_pred, y_downsample)

0.5510204081632653

In [30]:
from sklearn.metrics import roc_auc_score

In [38]:
prob_downsample = lr_downsample.predict_proba(X_downsample)

In [40]:
prob_downsample_positive = [p[1] for p in prob_downsample]

In [41]:
roc_auc_score(y_downsample, prob_downsample_positive)

0.5501874219075386

In [42]:
prob_upsample = lr_upsample.predict_proba(X_upsample)
prob_upsample_postitive = [p[1] for p in prob_upsample]

In [44]:
roc_auc_score(y_upsample, prob_upsample_postitive)

0.54297176408179

In [45]:
from sklearn.svm import SVC


In [46]:
svm_model = SVC(kernel='linear', class_weight='balanced', probability=True)
svm_model.fit(X,y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [47]:
svm_pred = svm_model.predict(X)

In [48]:
accuracy_score(svm_pred, y)

0.688

In [49]:
prob_svm = svm_model.predict_proba(X)

In [50]:
prob_svm_positive = [p[1] for p in prob_svm]

In [51]:
roc_auc_score(y, prob_svm_positive)

0.46947633219954643

In [52]:
svm_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [53]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
forest = RandomForestClassifier()
forest.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [55]:
forest_pred = forest.predict(X)

In [57]:
prob_forest = forest.predict_proba(X)

In [58]:
prob_forest_positive = [p[1] for p in prob_forest]

In [60]:
roc_auc_score(y, prob_forest_positive)

1.0